---
- include: setup.yml

- name: Ensure Kibana is started and enabled at boot.
  systemd:
    name: kibana
    state: started
    enabled: "{{ kibana_enabled_on_boot }}"
    daemon_reload: yes

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: "/opt/kibana/config/kibana.yml"
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
