---
- include: setup.yml

- name: Ensure Kibana is started and enabled at boot.
  systemd:
    name: kibana
    state: started
    enabled: "{{ kibana_enabled_on_boot }}"
    daemon_reload: yes

- name: Install X-Pack.
  become: true
  command: /usr/share/kibana/bin/kibana-plugin install x-pack
  when: kibana_xpack_enabled
  notify: restart kibana

- name: Copy Kibana configuration.
  template:
    src: kibana.yml.j2
    dest: /etc/kibana/kibana.yml
    owner: root
    group: root
    mode: 0644
  notify: restart kibana
